### ISSUE TITLE
Cache-Control header not set

### ISSUE THREAD

**Issue by bjornicus** [SocialEngine/docker-nginx-spa#4]
Chrome seems to be having some strange behavior when I update an app in this container, sometimes continuing to serve the old thing from a memory cache, and sometimes going and asking the server for the content.  I don't see an easy mechanism for overwriting the cache control headers without forking or copying and modifying the whole default.conf.  It would be nice to have an easy way to configure this (or maybe just some sane defaults that work well).

**Comment by smazurov** [comment]
thanks for your fix, sorry for 2 year lead time
